/**
 * Font wiring for the 14 selectable Amuse families.
 *
 * The original `useAmuseSettings` font table (`y`, beautified at
 * `app/_reference/useAmuseSettings.js:538-...`) is already ported verbatim to
 * `app/src/amuse/settings/registry.ts` as `FONTS`. This module is the single
 * place that turns a selected font id into:
 *
 *   - the Tailwind `fontClass` (e.g. `font-poppins`) applied by the skin's
 *     custom-font wrapper (`ce` in the original), and
 *   - the `titleClassName` / `artistClassName` / `songTimeClassName` override
 *     classes applied to the title (`ee`), artist (`de`) and time labels
 *     (`Ce`/`ke`),
 *   - the concrete CSS `font-family` stack the class resolves to (the
 *     `--font-*` tokens in `app/src/styles/tailwind.css`).
 *
 * It deliberately REUSES {@link FONTS} — it never re-declares the 14 families,
 * their ids, `fontClass` strings or override classes. Only the CSS
 * `font-family` stacks (which do not live in the registry) are defined here and
 * are asserted against `tailwind.css` in `fonts.test.ts`.
 *
 * The `@font-face` sources are self-hosted: Poppins under
 * `/webfonts/poppins/**`, the other 13 families under `/assets/**`
 * (`app/src/styles/fonts.css`, generated by `tools/extract-font-faces.mjs`).
 */

import {
  FONTS,
  getCurrentFont,
  type FontEntry,
  type FontScript,
} from '../settings/registry';

/**
 * First `font-<stem>` Tailwind token inside a `fontClass` string.
 *
 * `font-bagel-fat-one tracking-wider` -> `bagel-fat-one`; `font-poppins` ->
 * `poppins`. The stem is the suffix of the matching `--font-<stem>` token in
 * `tailwind.css`.
 */
export function fontTokenStem(fontClass: string): string | undefined {
  const token = fontClass.split(/\s+/).find((name) => name.startsWith('font-'));
  return token?.slice('font-'.length);
}

/**
 * CSS `font-family` stack per font id, copied VERBATIM from the `--font-*`
 * custom properties of `app/src/styles/tailwind.css` (Task 4 theme tokens).
 * `fonts.test.ts` asserts every entry against the real stylesheet so a drift
 * fails loudly.
 */
export const FONT_FAMILY_BY_ID: Record<string, string> = {
  poppins: 'Poppins,"Poppins Fallback",sans-serif',
  fredoka: '"Fredoka Variable",sans-serif',
  spacemono: '"Space Mono",monospace',
  silkscreen: 'Silkscreen,sans-serif',
  bagelFatOne: '"Bagel Fat One",sans-serif',
  gasoekOne: '"Gasoek One",sans-serif',
  zcoolKuaile: '"ZCOOL KuaiLe",sans-serif',
  zcoolQingkeHuangyou: '"ZCOOL QingKe HuangYou",sans-serif',
  singleDay: '"Single Day",sans-serif',
  jua: 'Jua,sans-serif',
  russoOne: '"Russo One",sans-serif',
  monomakh: 'Monomakh,sans-serif',
  notoSerifDisplay: '"Noto Serif Display Variable",serif',
  openDyslexic: 'OpenDyslexic,sans-serif',
};

/** Resolved wiring for one family. */
export interface FontWiring {
  id: string;
  name: string;
  /** Tailwind class applied by the skin's custom-font wrapper (`ce`). */
  fontClass: string;
  /** Matching `--font-<stem>` token in `tailwind.css` (e.g. `--font-jua`). */
  fontToken: string;
  /** CSS `font-family` stack the class resolves to. */
  fontFamily: string;
  /** Title (`ee`) override classes. */
  titleClassName: string;
  /** Artist (`de`) override classes. */
  artistClassName: string;
  /** Time labels (`Ce`/`ke`) override classes. */
  songTimeClassName: string;
  scripts: readonly FontScript[];
}

function wiringOf(font: FontEntry): FontWiring {
  const stem = fontTokenStem(font.fontClass);
  return {
    id: font.id,
    name: font.name,
    fontClass: font.fontClass,
    fontToken: stem ? `--font-${stem}` : '',
    fontFamily: FONT_FAMILY_BY_ID[font.id] ?? '',
    titleClassName: font.titleClassName,
    artistClassName: font.artistClassName,
    songTimeClassName: font.songTimeClassName,
    scripts: font.scripts,
  };
}

/** The 14 families' resolved wiring, in registry order. */
export const FONT_WIRING: readonly FontWiring[] = FONTS.map(wiringOf);

/** Resolves a font id (unknown ids fall back to `FONTS[0]`, per the original). */
export function getFontWiring(fontId: string): FontWiring {
  return wiringOf(getCurrentFont(fontId));
}

/** Tailwind class for the selected font (`ce` wrapper). */
export function getFontClass(fontId: string): string {
  return getCurrentFont(fontId).fontClass;
}

/** CSS `font-family` stack for the selected font. */
export function getFontFamily(fontId: string): string {
  return getFontWiring(fontId).fontFamily;
}

/** Title (`ee`) override classes for the selected font. */
export function getTitleClassName(fontId: string): string {
  return getCurrentFont(fontId).titleClassName;
}

/** Artist (`de`) override classes for the selected font. */
export function getArtistClassName(fontId: string): string {
  return getCurrentFont(fontId).artistClassName;
}

/** Song time (`Ce`/`ke`) override classes for the selected font. */
export function getSongTimeClassName(fontId: string): string {
  return getCurrentFont(fontId).songTimeClassName;
}
